version: "3.3"

services:
  app:
    container_name: "app"
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3001:3001
    volumes:
      - .:/app
    env_file:
      - .env

  mysql:
    container_name: "mysql"
    image: mysql:5.7
    env_file:
      - .env
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - ./_scripts/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:rw